#!/bin/bash

fpctarget=`Freepascal:bin/i386-aros/fpc -iTP`-`Freepascal:bin/i386-aros/fpc -iTO`
#echo $fpctarget
libpath='../lib/'$fpctarget
#libpath='pp:units/'$fpctarget'/fpgui/'

# Must we create the output directory?
if [ ! -d $libpath ]; then
  echo 'creating directory: '$libpath
  mkdir $libpath
  echo ' '
fi

Freepascal:bin/i386-aros/fpc -dRELEASE -dAROS @extrafpc.cfg  corelib/aros/fpgui_toolkit.pas

